version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: gasuaska/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: gasuaska/kittygram_frontend
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: gasuaska/kittygram_gateway
    volumes:
      - static:/staticfiles/
      - media:/app/media
    ports:
      - 9000:80
    depends_on:
      - db
      - backend
      - frontend
